# Generated by Django 5.2.6 on 2025-09-26 11:32

import attachments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=attachments.models.attachment_upload_to, validators=[attachments.models.validate_file_extension]),
        ),
    ]
